### ISSUE TITLE
MAJ ?

### ISSUE THREAD

**Issue by Valexandre** [AntoineAugusti/radars-france#3]
Hello Antoine,
Je voulais juste savoir si tu prévoyais une mise à jour de ce repo pour la rentrée 2019 ?
Merci !

**Comment by AntoineAugusti** [comment]
À ma connaissance il n'y a pas eu de mise à jour depuis novembre 2018 sur https://radars.securite-routiere.gouv.fr. Voir le footer.

Je me trompe ?

**Comment by AntoineAugusti** [comment]
Salut @Valexandre,

J'ai relancé la tâche de scrapping ce matin pour vérifier s'il y avait de nouvelles données disponibles malgré l'information indiquée dans le footer. La réponse est non 😢.
